Revert "fail test"
This reverts commit e0d3b23013e4a1097819031b3aa4a8777de1b509.

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -54,4 +54,6 @@ jobs:
 
       - name: Fail if 'Run Tests' failed
         if: steps.run_tests.outcome=='failure'
-        run: exit 1
+        run: |
+          echo "Step 'Run Tests' failed: Check 'Run Tests' and 'Print logs' for errors"
+          exit 1
